# Name of your GitHub Actions workflow.
name: Deploy to Netlify

# This workflow runs on pushes to the 'main' branch.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Use the latest version of Ubuntu as the runner.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies.
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run the build command for your project.
      - name: Build Project
        run: npm run build

      # Step 5: Deploy the built site to Netlify.
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          # This command deploys the '.next' directory to production.
          args: deploy --prod --dir=.next
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

