# Name of your GitHub Actions workflow.
name: Deploy to Netlify

# This workflow runs on pushes to the 'main' branch.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Use the latest version of Ubuntu as the runner.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies.
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run the build command for your project.
      # With the 'output: export' config, this will generate a static site in the 'out' folder.
      - name: Build Project
        run: npm run build

      # Step 5: Create Netlify config file to prevent Netlify from building AND running plugins.
      # This file tells Netlify where our pre-built site is and that no build command or plugins are needed.
      - name: Create Netlify Config
        run: |
          echo "[build]" > netlify.toml
          echo "command = \"\"" >> netlify.toml
          echo "publish = \"out\"" >> netlify.toml
          echo "" >> netlify.toml
          echo "[plugins]" >> netlify.toml

      # Step 6: Deploy the built site to Netlify.
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          # This command deploys the 'out' directory to production.
          args: deploy --prod --dir=out
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

